name: Setup p7zip fork
description: Setup/Install new p7zip fork (7zip CLI for Linux) with additional codecs for GitHub Actions
branding:
  icon: archive
  color: gray-dark
inputs:
  version:
    description:  p7zip fork version
    default: latest
  token:
    description: GitHub token to avoid API rate limiting
    default: ${{ github.token }}
    
runs:
  using: composite
  steps:
    - name: Get p7zip fork version
      id: version
      if: runner.os == 'Linux'
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/version.sh
      env:
        version: ${{ inputs.version }}
        GITHUB_TOKEN: ${{ inputs.token }}
        
    - name: Restore p7zip fork cache
      id: cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ runner.tool_cache }}/p7zip-fork
        key: p7zip-fork-${{ steps.version.outputs.version }}-${{ runner.os }}
        
    - name: Download p7zip fork
      if: '! steps.cache.outputs.cache-hit'
      shell: bash
      working-directory: ${{ runner.temp }}
      run: $GITHUB_ACTION_PATH/scripts/download.sh
      env:
        version: ${{ steps.version.outputs.version }}
        
    - name: Install p7zip fork on tool cache
      uses: AnimMouse/tool-cache@v1
      with:
        folder_name: p7zip-fork
        cache_hit: ${{ steps.cache.outputs.cache-hit }}
        
    - name: Save p7zip fork cache
      if: '! steps.cache.outputs.cache-hit'
      uses: actions/cache/save@v4
      with:
        path: ${{ runner.tool_cache }}/p7zip-fork
        key: p7zip-fork-${{ steps.version.outputs.version }}-${{ runner.os }}