name: Test setup-p7zip-fork
on:
  push:
    branches:
      - main
    paths:
      - action.yml
      - scripts/**
      - .github/workflows/test.yaml
  schedule:
    - cron: '7 11 1 * *'
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup p7zip fork using setup-p7zip-fork
        uses: AnimMouse/setup-p7zip-fork@main
        
      - name: Test p7zip fork installed by setup-p7zip-fork
        run: 7za i
        
      - name: Test original p7zip
        run: 7z i